### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by olimart** [olimart/yamail#7]
Hi Gena, could be due to large merge of last week but not sure. I'm not moving as fast I'd like but we're getting there.

```
  1) Error:
ServiceProviderTest#test_it_should_capture_basic_info_about_campaign:_rejected_count:
NoMethodError: undefined method `[]' for nil:NilClass
    test/models/service_provider_test.rb:83:in `block in <class:ServiceProviderTest>'

  2) Error:
ServiceProviderTest#test_it_should_capture_basic_info_about_campaign:_sent_count:
NoMethodError: undefined method `[]' for nil:NilClass
    test/models/service_provider_test.rb:77:in `block in <class:ServiceProviderTest>'

  3) Failure:
ServiceProviderTest#test_it_should_send_5_emails_and_get_'sent'_status [/home/runner/yamail/test/models/service_provider_test.rb:60]:
Failed assertion, no message given.

  4) Failure:
ServiceProviderTest#test_it_should_send_emails_and_get_1_'rejected'_status [/home/runner/yamail/test/models/service_provider_test.rb:66]:
Failed assertion, no message given.

  5) Failure:
ServiceProviderTest#test_it_should_send_emails_and_process_reject_reason [/home/runner/yamail/test/models/service_provider_test.rb:72]:
Failed assertion, no message given.

54 runs, 89 assertions, 3 failures, 2 errors, 0 skips
```

**Comment by croko** [comment]
in master?

**Comment by olimart** [comment]
yep
